export const tasksActionTypes = {
  SET_TASKS: "SET_TASKS",
  SET_NEW_TASK: "SET_NEW_TASK",
  REMOVE_TASK: "REMOVE_TASKS",
  UPDATE_TASK: "UPDATE_TASK",
  CHANGE_FILTER: "CHANGE_FILTER",
  SET_IS_EDIT: "SET_IS_EDIT",
  SET_NEW_BODY: "SET_NEW_BODY",
};
