export const allProductsActions = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
}

export const productActions = {
  SET_PRODUCT: "SET_PRODUCT",
  CLEAR_PRODCUT: "CLEAR_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
}

export const cartActions = {
  SET_CART: "SET_CART",
  ADD_NEW_ITEM_TO_CART: "ADD_NEW_ITEM_TO_CART",
  CLEAR_CART: "CLEAR_CART",
}

export const userActions = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  FAILED_TO_LOGIN: "FAILED_TO_LOGIN",
  CLOSE_LOGIN_FORM: "CLOSE_LOGIN_FORM",
  SHOW_LOGIN_FORM: "SHOW_LOGIN_FORM",
}

export const productEditForm = {
  SET_INPUTS: "SET_INPUTS",
  CLEAR_INPUTS: "CLEAR_INPUTS",
  START_EDIT_PRODUCT: "EDIT_PRODUCT",
  STOP_EDIT_PRODUCT: "STOP_EDIT_PRODUCT",
  UPDATE_INPUTS: "UPDATE_INPUTS"
}